version: "3.3"

services:

  traefik:
    image: "traefik:v2.8.1"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      # The HTTP port
      - 80:80
      # The Web UI (enabled by --api.insecure=true)
      - 8080:8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - lily2

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"
    networks:
      - lily2

  workshop81:
    build:
      context: .
      dockerfile: ./_dockerfiles/php8.1/Dockerfile
    container_name: workshop81_c
    volumes:
      - .:/var/www/html
    environment:
      - "PHP_ENABLE_XDEBUG=1"
      - "XDEBUG_CONFIG=idekey=PHPSTORM client_host=host.docker.internal xdebug.remote_port=9003 xdebug.discover_client_host=0 xdebug.start_with_request=yes xdebug.mode=develop,debug"
      - "XDEBUG_MODE=develop,debug"
      - "APACHE_DOCUMENT_ROOT=${DOCUMENT_ROOT}"
      - "PHP_IDE_CONFIG=serverName=workshop81.localhost"
    ports:
      - 9014:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.workshop81.rule=Host(`workshop81.localhost`)"
      - "traefik.http.routers.workshop81.entrypoints=web"
    env_file:
      - .env
    networks:
      - lily2

  workshop80:
    build:
      context: .
      dockerfile: ./_dockerfiles/php8.0/Dockerfile
    container_name: workshop80_c
    volumes:
      - .:/var/www/html
    environment:
      - "PHP_ENABLE_XDEBUG=1"
      - "XDEBUG_CONFIG=idekey=PHPSTORM client_host=host.docker.internal xdebug.remote_port=9003 xdebug.discover_client_host=0 xdebug.start_with_request=yes xdebug.mode=develop,debug"
      - "XDEBUG_MODE=develop,debug"
      - "APACHE_DOCUMENT_ROOT=${DOCUMENT_ROOT}"
      - "PHP_IDE_CONFIG=serverName=workshop80.localhost"
    ports:
      - 9015:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.workshop80.rule=Host(`workshop80.localhost`)"
      - "traefik.http.routers.workshop80.entrypoints=web"
    env_file:
      - .env
    networks:
      - lily2

  workshop74:
    build:
      context: .
      dockerfile: ./_dockerfiles/php7.4/Dockerfile
    container_name: workshop74_c
    volumes:
      - .:/var/www/html
    environment:
      - "PHP_ENABLE_XDEBUG=1"
      - "XDEBUG_CONFIG=idekey=PHPSTORM client_host=host.docker.internal xdebug.remote_port=9003 xdebug.discover_client_host=0 xdebug.start_with_request=yes xdebug.mode=develop,debug"
      - "XDEBUG_MODE=develop,debug"
      - "APACHE_DOCUMENT_ROOT=${DOCUMENT_ROOT}"
      - "PHP_IDE_CONFIG=serverName=workshop74.localhost"
    ports:
      - 9016:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.workshop74.rule=Host(`workshop74.localhost`)"
      - "traefik.http.routers.workshop74.entrypoints=web"
    env_file:
      - .env
    networks:
      - lily2

networks:
  lily2:

volumes:
  _dbdata:
